-- =========================================================================
-- V1 — Schema do domínio Infnet Hub
--
-- Estas tabelas guardam o estado atual. O histórico vem na V2.
--
-- As restrições vivem aqui, no banco, e não apenas nas anotações JPA: a
-- validação da aplicação roda antes da escrita e não impede que duas
-- requisições concorrentes passem juntas pela checagem. Quem arbitra é o banco.
-- =========================================================================

CREATE TABLE usuarios (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome           VARCHAR(100) NOT NULL,
    email          VARCHAR(150) NOT NULL,
    escola         VARCHAR(100),
    ultimo_bloco   VARCHAR(50),
    classe         VARCHAR(20),
    papel          VARCHAR(20)  NOT NULL,
    -- Metadados de auditoria (Spring Data JPA Auditing)
    criado_em      TIMESTAMP(6) NOT NULL,
    atualizado_em  TIMESTAMP(6) NOT NULL,
    criado_por     VARCHAR(150) NOT NULL,
    atualizado_por VARCHAR(150) NOT NULL,
    versao         BIGINT       NOT NULL,
    CONSTRAINT pk_usuarios PRIMARY KEY (id),
    -- Identidade institucional: é o que impede dois cadastros para a mesma pessoa.
    CONSTRAINT uk_usuarios_email UNIQUE (email),
    CONSTRAINT ck_usuarios_papel CHECK (papel IN ('ALUNO', 'PROFESSOR', 'SECRETARIA', 'COORDENADOR'))
);

CREATE TABLE posts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    titulo         VARCHAR(200),
    conteudo       TEXT         NOT NULL,
    autor_id       BIGINT       NOT NULL,
    curtidas       INTEGER      NOT NULL,
    criado_em      TIMESTAMP(6) NOT NULL,
    atualizado_em  TIMESTAMP(6) NOT NULL,
    criado_por     VARCHAR(150) NOT NULL,
    atualizado_por VARCHAR(150) NOT NULL,
    versao         BIGINT       NOT NULL,
    CONSTRAINT pk_posts PRIMARY KEY (id),
    CONSTRAINT fk_posts_autor FOREIGN KEY (autor_id) REFERENCES usuarios (id)
);

CREATE TABLE vagas (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    titulo         VARCHAR(150) NOT NULL,
    empresa        VARCHAR(150) NOT NULL,
    descricao      TEXT,
    localizacao    VARCHAR(100),
    tipo           VARCHAR(20)  NOT NULL,
    categoria      VARCHAR(100),
    ativo          BOOLEAN      NOT NULL,
    criador_id     BIGINT       NOT NULL,
    criado_em      TIMESTAMP(6) NOT NULL,
    atualizado_em  TIMESTAMP(6) NOT NULL,
    criado_por     VARCHAR(150) NOT NULL,
    atualizado_por VARCHAR(150) NOT NULL,
    versao         BIGINT       NOT NULL,
    CONSTRAINT pk_vagas PRIMARY KEY (id),
    CONSTRAINT fk_vagas_criador FOREIGN KEY (criador_id) REFERENCES usuarios (id),
    CONSTRAINT ck_vagas_tipo CHECK (tipo IN ('ESTAGIO', 'CLT', 'PJ', 'TRAINEE', 'AUTONOMO', 'EXTERIOR'))
);

CREATE TABLE comentarios (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    conteudo       TEXT         NOT NULL,
    post_id        BIGINT       NOT NULL,
    autor_id       BIGINT       NOT NULL,
    criado_em      TIMESTAMP(6) NOT NULL,
    atualizado_em  TIMESTAMP(6) NOT NULL,
    criado_por     VARCHAR(150) NOT NULL,
    atualizado_por VARCHAR(150) NOT NULL,
    versao         BIGINT       NOT NULL,
    CONSTRAINT pk_comentarios PRIMARY KEY (id),
    CONSTRAINT fk_comentarios_post FOREIGN KEY (post_id) REFERENCES posts (id),
    CONSTRAINT fk_comentarios_autor FOREIGN KEY (autor_id) REFERENCES usuarios (id)
);

CREATE TABLE curtidas (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    post_id        BIGINT       NOT NULL,
    usuario_id     BIGINT       NOT NULL,
    criado_em      TIMESTAMP(6) NOT NULL,
    atualizado_em  TIMESTAMP(6) NOT NULL,
    criado_por     VARCHAR(150) NOT NULL,
    atualizado_por VARCHAR(150) NOT NULL,
    versao         BIGINT       NOT NULL,
    CONSTRAINT pk_curtidas PRIMARY KEY (id),
    CONSTRAINT fk_curtidas_post FOREIGN KEY (post_id) REFERENCES posts (id),
    CONSTRAINT fk_curtidas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    -- Uma curtida por pessoa por post. É esta constraint — e não a checagem na
    -- aplicação — que mantém o contador desnormalizado de posts.curtidas honesto.
    CONSTRAINT uk_curtidas_post_usuario UNIQUE (post_id, usuario_id)
);

-- ── Índices ──────────────────────────────────────────────────────────────
-- Cada um existe por causa de uma consulta concreta da aplicação; índice sem
-- consulta correspondente só encarece a escrita.

-- Feed: ORDER BY criado_em DESC
CREATE INDEX idx_posts_criado_em ON posts (criado_em);
-- Posts de um autor
CREATE INDEX idx_posts_autor ON posts (autor_id);

-- Listagem de vagas: WHERE ativo = true ORDER BY criado_em DESC (índice composto
-- na mesma ordem do predicado e da ordenação)
CREATE INDEX idx_vagas_ativo_criado_em ON vagas (ativo, criado_em);
CREATE INDEX idx_vagas_tipo ON vagas (tipo);
CREATE INDEX idx_vagas_criador ON vagas (criador_id);

-- Comentários de um post em ordem cronológica
CREATE INDEX idx_comentarios_post_criado_em ON comentarios (post_id, criado_em);
CREATE INDEX idx_comentarios_autor ON comentarios (autor_id);

-- Curtidas por post (contagem) e por usuário
CREATE INDEX idx_curtidas_post ON curtidas (post_id);
CREATE INDEX idx_curtidas_usuario ON curtidas (usuario_id);

-- Filtro por papel na busca de usuários
CREATE INDEX idx_usuarios_papel ON usuarios (papel);
