-- =========================================================================
-- V4 — Caixa de saída das mensagens (transactional outbox)
--
-- Todo evento que o core anuncia passa por esta tabela antes de chegar ao
-- broker. É gravado na MESMA transação da alteração que o originou: se o
-- usuário foi salvo, o evento foi salvo; se a transação voltou atrás, os dois
-- somem juntos. Não existe estado em que um aconteceu e o outro não.
--
-- Um processo separado (o relay) lê as linhas pendentes, publica no RabbitMQ,
-- espera a confirmação do broker e só então preenche publicado_em.
-- =========================================================================

CREATE TABLE outbox_mensagem (
    -- Sequência, e não o UUID, como chave: é ela que dá a ordem de publicação.
    -- Dois eventos na mesma transação podem ter o mesmo criado_em; a
    -- sequência nunca empata.
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensagem_id   UUID          NOT NULL,
    tipo          VARCHAR(100)  NOT NULL,
    rota          VARCHAR(100)  NOT NULL,
    chave         VARCHAR(100)  NOT NULL,
    payload       TEXT          NOT NULL,
    criado_em     TIMESTAMP     NOT NULL,
    publicado_em  TIMESTAMP,
    tentativas    INTEGER       NOT NULL DEFAULT 0,
    ultimo_erro   VARCHAR(500),

    CONSTRAINT uk_outbox_mensagem_id UNIQUE (mensagem_id)
);

-- O relay só lê o que está pendente, e em ordem. O índice parcial fica do
-- tamanho da fila de espera, não do histórico inteiro: com o tempo a tabela
-- cresce, mas as linhas publicadas saem do índice.
CREATE INDEX idx_outbox_pendentes ON outbox_mensagem (id) WHERE publicado_em IS NULL;
