-- =========================================================================
-- V6 — Saga de expurgo (LGPD)
--
-- Remover uma pessoa do sistema envolve três bancos que nenhuma transação
-- alcança ao mesmo tempo. Esta migração cria o que falta para tratar isso como
-- um PROCESSO com estados observáveis, e não como um DELETE otimista.
-- =========================================================================

-- ── 1. O bloqueio ────────────────────────────────────────────────────────
-- Enquanto a saga corre, a pessoa não pode aparecer nem agir — mas o registro
-- precisa continuar existindo, porque a saga pode ser revertida. É a diferença
-- entre "sumiu" e "foi apagado", e é ela que torna a compensação possível.
--
-- Depois de concluída a saga, a coluna permanece verdadeira: o registro segue
-- no banco, anonimizado, sustentando as publicações e os comentários que a
-- pessoa deixou. Para a API, os dois casos são o mesmo — não existe mais.
ALTER TABLE usuarios
    ADD COLUMN removido BOOLEAN NOT NULL DEFAULT FALSE;

COMMENT ON COLUMN usuarios.removido IS
    'Fora do sistema: bloqueado durante a saga de expurgo, ou já anonimizado por ela.';

-- Toda listagem filtra por esta coluna, e quem está removido é minoria.
CREATE INDEX idx_usuarios_ativos ON usuarios (id) WHERE removido = FALSE;

-- ── 2. O processo ────────────────────────────────────────────────────────
CREATE TABLE expurgo_lgpd (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Sem chave estrangeira de propósito: o registro do expurgo precisa
    -- sobreviver ao usuário se um dia a anonimização virar exclusão.
    usuario_id      BIGINT        NOT NULL,

    estado          VARCHAR(20)   NOT NULL,
    solicitado_por  BIGINT,
    solicitado_em   TIMESTAMP     NOT NULL,
    encerrado_em    TIMESTAMP,

    -- Preenchido na recusa. É o que a secretaria lê para entender por que a
    -- pessoa continua no sistema depois de ter pedido a remoção.
    motivo          VARCHAR(300),

    -- Preenchido na conclusão: o que ficou no boletim, sem identificação.
    registros_mantidos INTEGER,

    CONSTRAINT ck_expurgo_estado
        CHECK (estado IN ('SOLICITADO', 'CONCLUIDO', 'REVERTIDO'))
);

-- Uma pessoa não pode ter dois expurgos em andamento ao mesmo tempo: o segundo
-- pedido encontraria o primeiro no meio do caminho e os dois disputariam o
-- mesmo bloqueio. O índice parcial permite repetir o pedido depois que o
-- anterior terminou — inclusive depois de uma recusa, que é o caso comum.
CREATE UNIQUE INDEX uk_expurgo_em_andamento
    ON expurgo_lgpd (usuario_id) WHERE estado = 'SOLICITADO';

CREATE INDEX idx_expurgo_usuario ON expurgo_lgpd (usuario_id, id DESC);

-- ── 3. O core passa a consumir ───────────────────────────────────────────
-- Até aqui ele só publicava. Na saga, quem começa precisa ouvir a resposta —
-- e todo consumidor precisa da mesma defesa contra a entrega repetida.
CREATE TABLE mensagem_processada (
    mensagem_id   UUID          PRIMARY KEY,
    tipo          VARCHAR(100)  NOT NULL,
    processada_em TIMESTAMP     NOT NULL
);

COMMENT ON TABLE mensagem_processada IS
    'Idempotência do consumidor: gravada na MESMA transação do efeito.';
