-- =========================================================================
-- V1 — Schema do Desempenho Acadêmico
--
-- Banco PRÓPRIO do boletim-service, separado do banco do infnethub-core. Não
-- há chave estrangeira apontando para usuarios: aquela tabela vive em outra
-- instância de PostgreSQL, e uma FK entre bancos não existe. O vínculo com o
-- aluno é feito por aluno_id, um identificador guardado por valor — o mesmo
-- id que o core atribui ao Usuario.
--
-- Isso tem um preço, e ele é assumido de propósito: o banco não impede que se
-- grave um aluno_id inexistente. A integridade referencial entre serviços deixa
-- de ser garantida por constraint e passa a ser responsabilidade da aplicação,
-- que confirma a existência do aluno no core antes de gravar. É a troca padrão
-- de Database per Service: perde-se a FK, ganha-se a independência de evoluir,
-- migrar e reimplantar cada banco sem coordenar com o outro.
--
-- A divisão das tabelas segue uma fronteira que o domínio já tem:
--
--   CATÁLOGO   o que o curso é, igual para todos os alunos
--              bloco · disciplina · competencia
--
--   PERCURSO   o que ESTE aluno fez, e como foi avaliado
--              matricula · avaliacao · atividade_academica
--
-- Sem essa separação, o nome de uma disciplina e o texto de cada competência
-- se repetiriam a cada aluno matriculado, e corrigir um erro de digitação
-- viraria um UPDATE em massa com risco de deixar registros divergentes.
-- =========================================================================

-- ── CATÁLOGO ─────────────────────────────────────────────────────────────

CREATE TABLE bloco (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    numero         INTEGER      NOT NULL,
    titulo         VARCHAR(150) NOT NULL,
    criado_em      TIMESTAMP(6) NOT NULL,
    atualizado_em  TIMESTAMP(6) NOT NULL,
    versao         BIGINT       NOT NULL,
    CONSTRAINT pk_bloco PRIMARY KEY (id),
    -- O bloco é identificado pela posição no curso; dois blocos 3 seriam
    -- ambiguidade, não dado.
    CONSTRAINT uk_bloco_numero UNIQUE (numero),
    CONSTRAINT ck_bloco_numero CHECK (numero > 0)
);

CREATE TABLE disciplina (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    bloco_id           BIGINT       NOT NULL,
    nome               VARCHAR(150) NOT NULL,
    tipo               VARCHAR(20)  NOT NULL,
    carga_horaria      INTEGER      NOT NULL,
    -- Planejamento de Curso e Carreira e Fluência em IA não reprovam por
    -- frequência. É atributo da disciplina, não do aluno: vale para todos.
    isenta_frequencia  BOOLEAN      NOT NULL DEFAULT FALSE,
    criado_em          TIMESTAMP(6) NOT NULL,
    atualizado_em      TIMESTAMP(6) NOT NULL,
    versao             BIGINT       NOT NULL,
    CONSTRAINT pk_disciplina PRIMARY KEY (id),
    CONSTRAINT fk_disciplina_bloco FOREIGN KEY (bloco_id) REFERENCES bloco (id),
    CONSTRAINT uk_disciplina_bloco_nome UNIQUE (bloco_id, nome),
    CONSTRAINT ck_disciplina_tipo CHECK (tipo IN ('REGULAR', 'PROJETO_BLOCO')),
    CONSTRAINT ck_disciplina_carga CHECK (carga_horaria > 0)
);

CREATE TABLE competencia (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    disciplina_id  BIGINT       NOT NULL,
    nome           VARCHAR(200) NOT NULL,
    ordem          INTEGER      NOT NULL,
    criado_em      TIMESTAMP(6) NOT NULL,
    atualizado_em  TIMESTAMP(6) NOT NULL,
    versao         BIGINT       NOT NULL,
    CONSTRAINT pk_competencia PRIMARY KEY (id),
    CONSTRAINT fk_competencia_disciplina FOREIGN KEY (disciplina_id) REFERENCES disciplina (id),
    -- A ordem é do plano de ensino e precisa sair estável na listagem; sem
    -- ela o boletim reordenaria as competências a cada consulta.
    CONSTRAINT uk_competencia_disciplina_ordem UNIQUE (disciplina_id, ordem)
);

-- ── PERCURSO DO ALUNO ────────────────────────────────────────────────────

CREATE TABLE matricula (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    -- Referência ao Usuario do infnethub-core, guardada por valor. Ver a nota
    -- no cabeçalho sobre a ausência de FK entre bancos.
    aluno_id              BIGINT       NOT NULL,
    disciplina_id         BIGINT       NOT NULL,
    periodo               VARCHAR(10)  NOT NULL,
    presenca_percentual   INTEGER      NOT NULL,
    tps_total             INTEGER      NOT NULL,
    tps_atraso            INTEGER      NOT NULL,
    tps_pendentes         INTEGER      NOT NULL,
    criado_em             TIMESTAMP(6) NOT NULL,
    atualizado_em         TIMESTAMP(6) NOT NULL,
    versao                BIGINT       NOT NULL,
    CONSTRAINT pk_matricula PRIMARY KEY (id),
    CONSTRAINT fk_matricula_disciplina FOREIGN KEY (disciplina_id) REFERENCES disciplina (id),
    -- Um aluno cursa a mesma disciplina uma vez por período. Repetir a
    -- disciplina em outro trimestre é caso legítimo e continua permitido.
    CONSTRAINT uk_matricula_aluno_disciplina_periodo UNIQUE (aluno_id, disciplina_id, periodo),
    CONSTRAINT ck_matricula_presenca CHECK (presenca_percentual BETWEEN 0 AND 100),
    CONSTRAINT ck_matricula_tps CHECK (
        tps_total >= 0
        AND tps_atraso    BETWEEN 0 AND tps_total
        AND tps_pendentes BETWEEN 0 AND tps_total
    )
);

-- Toda consulta do boletim parte do aluno; sem este índice, montar a página de
-- um aluno exigiria varrer as matrículas de todos.
CREATE INDEX idx_matricula_aluno ON matricula (aluno_id);

CREATE TABLE avaliacao (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    matricula_id    BIGINT       NOT NULL,
    competencia_id  BIGINT       NOT NULL,
    -- NULL é estado de domínio, não ausência de dado: significa competência
    -- ainda em avaliação. É o que o boletim mostra como "—" e o que faz a
    -- disciplina aparecer como "Cursando" em vez de aprovada ou reprovada.
    -- ND é diferente: é um resultado, e reprova.
    conceito        VARCHAR(3),
    avaliado_em     TIMESTAMP(6),
    criado_em       TIMESTAMP(6) NOT NULL,
    atualizado_em   TIMESTAMP(6) NOT NULL,
    versao          BIGINT       NOT NULL,
    CONSTRAINT pk_avaliacao PRIMARY KEY (id),
    CONSTRAINT fk_avaliacao_matricula FOREIGN KEY (matricula_id) REFERENCES matricula (id),
    CONSTRAINT fk_avaliacao_competencia FOREIGN KEY (competencia_id) REFERENCES competencia (id),
    -- Uma competência tem um resultado por matrícula. É a constraint que
    -- impede o mesmo conceito lançado duas vezes por requisições simultâneas.
    CONSTRAINT uk_avaliacao_matricula_competencia UNIQUE (matricula_id, competencia_id),
    CONSTRAINT ck_avaliacao_conceito CHECK (conceito IS NULL OR conceito IN ('DML', 'DL', 'D', 'ND'))
);

CREATE INDEX idx_avaliacao_matricula ON avaliacao (matricula_id);

-- Extensão, eletivas, estágio e atividades complementares. Estão numa tabela
-- só, e não em quatro: têm exatamente os mesmos atributos e diferem apenas na
-- categoria e nas regras de contagem — que são da aplicação, não do schema.
CREATE TABLE atividade_academica (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    aluno_id             BIGINT       NOT NULL,
    categoria            VARCHAR(20)  NOT NULL,
    nome                 VARCHAR(200) NOT NULL,
    carga_horaria        INTEGER      NOT NULL,
    periodo              VARCHAR(10),
    status               VARCHAR(20)  NOT NULL,
    -- Só as eletivas exigem presença; nas demais categorias fica nulo.
    presenca_percentual  INTEGER,
    criado_em            TIMESTAMP(6) NOT NULL,
    atualizado_em        TIMESTAMP(6) NOT NULL,
    versao               BIGINT       NOT NULL,
    CONSTRAINT pk_atividade_academica PRIMARY KEY (id),
    CONSTRAINT ck_atividade_categoria CHECK (categoria IN ('EXTENSAO', 'ELETIVA', 'ESTAGIO', 'COMPLEMENTAR')),
    CONSTRAINT ck_atividade_status CHECK (status IN ('CONCLUIDO', 'EM_CURSO', 'NAO_CONCLUIDO')),
    CONSTRAINT ck_atividade_carga CHECK (carga_horaria > 0),
    CONSTRAINT ck_atividade_presenca CHECK (presenca_percentual IS NULL OR presenca_percentual BETWEEN 0 AND 100)
);

CREATE INDEX idx_atividade_aluno_categoria ON atividade_academica (aluno_id, categoria);
