-- =========================================================================
-- V3 — Caixa de saída do boletim-service
--
-- Até aqui este serviço só consumia. Com a saga de expurgo ele passa a
-- responder — e uma resposta perdida é pior do que um evento perdido: o
-- processo fica parado para sempre, sem que ninguém saiba que está parado.
--
-- Mesmo padrão do core, pelo mesmo motivo: a confirmação é gravada na MESMA
-- transação da anonimização. Ou a réplica foi anonimizada E a resposta está
-- na fila de saída, ou nenhuma das duas coisas aconteceu. Não existe estado
-- em que o boletim anonimizou e o core nunca ficou sabendo.
-- =========================================================================

CREATE TABLE outbox_mensagem (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensagem_id   UUID          NOT NULL,
    tipo          VARCHAR(100)  NOT NULL,
    rota          VARCHAR(100)  NOT NULL,
    chave         VARCHAR(100)  NOT NULL,
    payload       TEXT          NOT NULL,
    atraso_ms     BIGINT        NOT NULL DEFAULT 0,
    criado_em     TIMESTAMP     NOT NULL,
    publicado_em  TIMESTAMP,
    tentativas    INTEGER       NOT NULL DEFAULT 0,
    ultimo_erro   VARCHAR(500),

    CONSTRAINT uk_outbox_mensagem_id UNIQUE (mensagem_id)
);

CREATE INDEX idx_outbox_pendentes ON outbox_mensagem (id) WHERE publicado_em IS NULL;
