-- =========================================================================
-- V1 — Schema do serviço de Notificações
--
-- Banco próprio, terceira instância de PostgreSQL do sistema. Nada aqui é
-- escrito por outro serviço, e nada aqui é lido por outro serviço: o que chega,
-- chega por evento; o que sai, sai pela API deste serviço.
-- =========================================================================

-- Uma notificação é de UM destinatário. Uma vaga publicada para cinquenta
-- alunos vira cinquenta linhas (fan-out na escrita): ler "as minhas" é então
-- uma consulta por índice, sem junção, e marcar como lida é um UPDATE numa
-- linha que é só daquela pessoa.
CREATE TABLE notificacao (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destinatario_id      BIGINT        NOT NULL,
    tipo                 VARCHAR(20)   NOT NULL,
    texto                VARCHAR(300)  NOT NULL,
    link                 VARCHAR(200),
    -- Com fuso (TIMESTAMPTZ, lido como Instant): o serviço roda em UTC no
    -- contêiner e o navegador no horário local. Sem fuso, a data sairia na API
    -- sem o sufixo Z, o navegador a leria como horário local, e "agora"
    -- apareceria como "há 3h" na tela de quem está em Brasília.
    criada_em            TIMESTAMPTZ   NOT NULL,
    lida_em              TIMESTAMPTZ,

    -- O evento que originou a notificação. Com a chave única abaixo, o mesmo
    -- evento entregue duas vezes não gera duas notificações para a mesma
    -- pessoa — a idempotência sai do próprio modelo, e não só do registro de
    -- mensagens processadas.
    mensagem_origem_id   UUID          NOT NULL,

    CONSTRAINT uk_notificacao_origem_destinatario UNIQUE (mensagem_origem_id, destinatario_id),
    CONSTRAINT ck_notificacao_tipo CHECK (tipo IN ('BOAS_VINDAS', 'CURTIDA', 'COMENTARIO', 'VAGA'))
);

-- A consulta de todo carregamento de tela: as mais recentes de uma pessoa.
CREATE INDEX idx_notificacao_destinatario_recentes ON notificacao (destinatario_id, criada_em DESC);

-- A contagem do sino: não lidas de uma pessoa. Índice parcial, do tamanho do
-- que falta ler, não do histórico.
CREATE INDEX idx_notificacao_nao_lidas ON notificacao (destinatario_id) WHERE lida_em IS NULL;

-- Quem pode receber aviso de vaga nova. Mantido pelos eventos de usuário, e
-- sem nome nem e-mail: para decidir quem recebe basta saber quem existe e qual
-- é o papel. O texto da notificação vem pronto no evento que a origina.
--
-- Removido vira marca (tombstone), não DELETE. Com vários consumidores em
-- paralelo, um UsuarioCadastrado atrasado poderia chegar depois do
-- UsuarioRemovido e ressuscitar o destinatário; a marca, com a versão, impede.
CREATE TABLE destinatario (
    usuario_id       BIGINT       PRIMARY KEY,
    papel            VARCHAR(20)  NOT NULL,
    versao_origem    BIGINT       NOT NULL,
    removido         BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE mensagem_processada (
    mensagem_id    UUID          PRIMARY KEY,
    tipo           VARCHAR(100)  NOT NULL,
    processada_em  TIMESTAMP     NOT NULL
);
